// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh_u-8NEz12Jy616-GWXyMk5eKFPWJTSU',
    appId: '1:364109033257:web:31bff3b8828e4253ce5138',
    messagingSenderId: '364109033257',
    projectId: 'belize-loan-verification',
    authDomain: 'belize-loan-verification.firebaseapp.com',
    storageBucket: 'belize-loan-verification.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMpBujzPxVhn_jx8nKG2yRoA_EtqhZxGQ',
    appId: '1:364109033257:android:53d1a72c61420f97ce5138',
    messagingSenderId: '364109033257',
    projectId: 'belize-loan-verification',
    storageBucket: 'belize-loan-verification.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo2K6Xzacb82bU8i1KFmM6KG5ewKPLjJU',
    appId: '1:364109033257:ios:006191e892e90d83ce5138',
    messagingSenderId: '364109033257',
    projectId: 'belize-loan-verification',
    storageBucket: 'belize-loan-verification.firebasestorage.app',
    iosBundleId: 'com.example.belizelogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo2K6Xzacb82bU8i1KFmM6KG5ewKPLjJU',
    appId: '1:364109033257:ios:006191e892e90d83ce5138',
    messagingSenderId: '364109033257',
    projectId: 'belize-loan-verification',
    storageBucket: 'belize-loan-verification.firebasestorage.app',
    iosBundleId: 'com.example.belizelogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCh_u-8NEz12Jy616-GWXyMk5eKFPWJTSU',
    appId: '1:364109033257:web:cc9bc0bd30221e85ce5138',
    messagingSenderId: '364109033257',
    projectId: 'belize-loan-verification',
    authDomain: 'belize-loan-verification.firebaseapp.com',
    storageBucket: 'belize-loan-verification.firebasestorage.app',
  );
}
